# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a1214bbce254a0063cf8770388e8f72fbc0ec1f9658b8448a33fd983c4702e5e79ae4a7fd2980be032306d1015ebe250b846da5687d2d3d6f59404054d4d6c0

test:
  secret_key_base: a16f43badf5696fc001a4086bae73c0404d4ddfeb90a894ce9f2316ff31a84e5c5e14c622f1161424730023a0f784efd6ffe2cc592d7edc7c6d77ede2a536132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
